apply plugin: 'com.android.application'

android {
    compileSdk = 34
    namespace = "com.wafitz.pixelspacebase"

    buildTypes {
        release {
            shrinkResources = true
            minifyEnabled = true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    defaultConfig {
        minSdk = 9
        targetSdk = 34
    }
}

dependencies {
    implementation project(':pd-classes')
    testImplementation 'junit:junit:4.13.2'
}
