apply plugin: 'com.android.application'

android {
    compileSdkVersion 34
    namespace "com.wafitz.pixelspacebase"

    buildTypes {
        release {
            shrinkResources true
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    defaultConfig {
        minSdkVersion 9
        targetSdkVersion 34
    }
}

dependencies {
    implementation project(':pd-classes')
    testImplementation 'junit:junit:4.13.2'
}
