badges.endorsed=Badge endorsed: %s
badges.new_super=New super badge: %s
badges.new=New badge: %s
badges$badge.monsters_slain_1=10 enemies slain
badges$badge.monsters_slain_2=50 enemies slain
badges$badge.monsters_slain_3=150 enemies slain
badges$badge.monsters_slain_4=250 enemies slain
badges$badge.parts_collected_1=100 parts collected
badges$badge.parts_collected_2=500 parts collected
badges$badge.parts_collected_3=2500 parts collected
badges$badge.parts_collected_4=7500 parts collected
badges$badge.level_reached_1=Level 6 reached
badges$badge.level_reached_2=Level 12 reached
badges$badge.level_reached_3=Level 18 reached
badges$badge.level_reached_4=Level 24 reached
badges$badge.all_plasmids_identified=All plasmids identified
badges$badge.all_upgrades_identified=All upgrades identified
badges$badge.all_modules_identified=All modules identified
badges$badge.all_blasters_identified=All blasters identified
badges$badge.all_items_identified=All plasmids, upgrades, modules & blasters identified
badges$badge.all_containers_bought=All containers bought
badges$badge.all_containers_made=All containers made
badges$badge.death_from_fire=Death from fire
badges$badge.death_from_poison=Death from poison
badges$badge.death_from_gas=Death from toxic gas
badges$badge.death_from_hunger=Death from hunger
badges$badge.death_from_enhancement=Death from an enhancement
badges$badge.death_from_falling=Death from falling down
badges$badge.yasd=Death from fire, poison, toxic gas & hunger
badges$badge.boss_slain_1=1st boss slain
badges$badge.boss_slain_2=2nd boss slain
badges$badge.boss_slain_3=3rd boss slain
badges$badge.boss_slain_4=4th boss slain
badges$badge.boss_slain_1_all_classes=1st boss slain by Commander, DM-3000, Shapeshifter & Captain
badges$badge.boss_slain_3_all_subclasses=3rd boss slain by every advanced combat protocol
badges$badge.haggler_module=Haggler Module obtained
badges$badge.hagglermodule=Haggler Module obtained
badges$badge.thorns_module=Thorns Module obtained
badges$badge.thornmodule=Thorns Module obtained
badges$badge.strength_attained_1=13 points of Strength attained
badges$badge.strength_attained_2=15 points of Strength attained
badges$badge.strength_attained_3=17 points of Strength attained
badges$badge.strength_attained_4=19 points of Strength attained
badges$badge.food_eaten_1=10 rations eaten
badges$badge.food_eaten_2=20 rations eaten
badges$badge.food_eaten_3=30 rations eaten
badges$badge.food_eaten_4=40 rations eaten
badges$badge.item_level_1=Item of level 3 acquired
badges$badge.item_level_2=Item of level 6 acquired
badges$badge.item_level_3=Item of level 9 acquired
badges$badge.item_level_4=Item of level 12 acquired
badges$badge.rare=All rare monsters slain
badges$badge.victory=Escape pod override obtained
badges$badge.victory_all_classes=Escape pod override obtained by Commander, DM-3000, Shapeshifter & Captain
badges$badge.mastery_combo=10-hit combo
badges$badge.plasmids_made_1=3 plasmids made
badges$badge.plasmids_made_2=6 plasmids made
badges$badge.plasmids_made_3=9 plasmids made
badges$badge.plasmids_made_4=12 plasmids made
badges$badge.no_monsters_slain=Level completed without killing any enemies
badges$badge.grim_weapon=Enemy killed by an execution enhancement
badges$badge.waterthings=6 water things killed
badges$badge.night_hunter=15 enemies killed at nighttime
badges$badge.games_played_1=10 games played
badges$badge.games_played_2=100 games played
badges$badge.games_played_3=500 games played
badges$badge.games_played_4=2000 games played
badges$badge.happy_end=Happy end
badges$badge.champion=Challenge won
badges$badge.supporter=Thanks for your support!

challenges.no_food=On diet
challenges.no_armor=Faith is my armor
challenges.no_healing=Pharmacophobia
challenges.no_herbalism=Barren land
challenges.swarm_intelligence=Swarm intelligence
challenges.darkness=Into darkness
challenges.no_upgrades=No tech
journal$feature.well_of_health=Medical Terminal
journal$feature.well_of_awareness=Knowledgebase Terminal
journal$feature.well_of_transmutation=Atomic Diffusion Terminal
journal$feature.craft=Fabricator
journal$feature.garden=Medical Bay
journal$feature.oldWarBot=Old War Bot
journal$feature.hologram=Hologram
journal$feature.gunsmith=Quartermaster
journal$feature.troll=Chief Engineer
journal$feature.arp=Y
journal$feature.health_terminal=Medical Terminal
journal$feature.knowledge_terminal=Knowledgebase Terminal
journal$feature.diffusion_terminal=Atomic Diffusion Terminal
journal$feature.crafting=Fabricator
journal$feature.medicalbay=Medical Bay
journal$feature.oldwarbot=Old War Bot

rankings$record.something=Killed by Something
